package response

// ResponseCode represents standardized response codes
type ResponseCode string

// Success codes
const (
	// General success codes
	SUCCESS             ResponseCode = "SUCCESS"
	CREATED             ResponseCode = "CREATED"
	UPDATED             ResponseCode = "UPDATED"
	DELETED             ResponseCode = "DELETED"
	RETRIEVED           ResponseCode = "RETRIEVED"
	OPERATION_COMPLETED ResponseCode = "OPERATION_COMPLETED"
)

// User-related codes
const (
	// User success codes
	USER_CREATED          ResponseCode = "USER_CREATED"
	USER_UPDATED          ResponseCode = "USER_UPDATED"
	USER_DELETED          ResponseCode = "USER_DELETED"
	USER_RETRIEVED        ResponseCode = "USER_RETRIEVED"
	USER_PASSWORD_CHANGED ResponseCode = "USER_PASSWORD_CHANGED"
	USER_ACTIVATED        ResponseCode = "USER_ACTIVATED"
	USER_DEACTIVATED      ResponseCode = "USER_DEACTIVATED"
	USER_SUSPENDED        ResponseCode = "USER_SUSPENDED"
	USERS_LISTED          ResponseCode = "USERS_LISTED"
	USER_STATS_RETRIEVED  ResponseCode = "USER_STATS_RETRIEVED"
	USERS_BULK_UPDATED    ResponseCode = "USERS_BULK_UPDATED"

	// User error codes
	USER_NOT_FOUND         ResponseCode = "USER_NOT_FOUND"
	USER_ALREADY_EXISTS    ResponseCode = "USER_ALREADY_EXISTS"
	USER_EMAIL_EXISTS      ResponseCode = "USER_EMAIL_EXISTS"
	USER_USERNAME_EXISTS   ResponseCode = "USER_USERNAME_EXISTS"
	USER_INVALID_ID        ResponseCode = "USER_INVALID_ID"
	USER_INVALID_STATUS    ResponseCode = "USER_INVALID_STATUS"
	USER_CREATION_FAILED   ResponseCode = "USER_CREATION_FAILED"
	USER_UPDATE_FAILED     ResponseCode = "USER_UPDATE_FAILED"
	USER_DELETE_FAILED     ResponseCode = "USER_DELETE_FAILED"
	USER_PASSWORD_INVALID  ResponseCode = "USER_PASSWORD_INVALID"
	USER_PASSWORD_TOO_WEAK ResponseCode = "USER_PASSWORD_TOO_WEAK"
	USER_PASSWORD_SAME     ResponseCode = "USER_PASSWORD_SAME"
	USER_UNAUTHORIZED      ResponseCode = "USER_UNAUTHORIZED"
	USER_SUSPENDED_ACCOUNT ResponseCode = "USER_SUSPENDED_ACCOUNT"
	USER_INACTIVE_ACCOUNT  ResponseCode = "USER_INACTIVE_ACCOUNT"
)

// Authentication codes
const (
	// Auth success codes
	AUTH_LOGIN_SUCCESS    ResponseCode = "AUTH_LOGIN_SUCCESS"
	AUTH_LOGOUT_SUCCESS   ResponseCode = "AUTH_LOGOUT_SUCCESS"
	AUTH_TOKEN_REFRESHED  ResponseCode = "AUTH_TOKEN_REFRESHED"
	AUTH_MFA_ENABLED      ResponseCode = "AUTH_MFA_ENABLED"
	AUTH_MFA_DISABLED     ResponseCode = "AUTH_MFA_DISABLED"
	AUTH_MFA_VALIDATED    ResponseCode = "AUTH_MFA_VALIDATED"
	AUTH_BACKUP_CODES_GEN ResponseCode = "AUTH_BACKUP_CODES_GENERATED"
	AUTH_SESSION_REVOKED  ResponseCode = "AUTH_SESSION_REVOKED"
	AUTH_SESSIONS_LISTED  ResponseCode = "AUTH_SESSIONS_LISTED"

	// Auth error codes
	AUTH_INVALID_CREDENTIALS   ResponseCode = "AUTH_INVALID_CREDENTIALS"
	AUTH_TOKEN_EXPIRED         ResponseCode = "AUTH_TOKEN_EXPIRED"
	AUTH_TOKEN_INVALID         ResponseCode = "AUTH_TOKEN_INVALID"
	AUTH_TOKEN_MISSING         ResponseCode = "AUTH_TOKEN_MISSING"
	AUTH_REFRESH_TOKEN_INVALID ResponseCode = "AUTH_REFRESH_TOKEN_INVALID"
	AUTH_MFA_REQUIRED          ResponseCode = "AUTH_MFA_REQUIRED"
	AUTH_MFA_INVALID_CODE      ResponseCode = "AUTH_MFA_INVALID_CODE"
	AUTH_MFA_NOT_ENABLED       ResponseCode = "AUTH_MFA_NOT_ENABLED"
	AUTH_SESSION_NOT_FOUND     ResponseCode = "AUTH_SESSION_NOT_FOUND"
	AUTH_LOGIN_FAILED          ResponseCode = "AUTH_LOGIN_FAILED"
	AUTH_LOGOUT_FAILED         ResponseCode = "AUTH_LOGOUT_FAILED"
)

// Tenant-related codes
const (
	// Tenant success codes
	TENANT_CREATED       ResponseCode = "TENANT_CREATED"
	TENANT_UPDATED       ResponseCode = "TENANT_UPDATED"
	TENANT_DELETED       ResponseCode = "TENANT_DELETED"
	TENANT_RETRIEVED     ResponseCode = "TENANT_RETRIEVED"
	TENANT_ACTIVATED     ResponseCode = "TENANT_ACTIVATED"
	TENANT_DEACTIVATED   ResponseCode = "TENANT_DEACTIVATED"
	TENANT_SUSPENDED     ResponseCode = "TENANT_SUSPENDED"
	TENANTS_LISTED       ResponseCode = "TENANTS_LISTED"
	TENANTS_BULK_UPDATED ResponseCode = "TENANTS_BULK_UPDATED"

	// Tenant error codes
	TENANT_NOT_FOUND       ResponseCode = "TENANT_NOT_FOUND"
	TENANT_ALREADY_EXISTS  ResponseCode = "TENANT_ALREADY_EXISTS"
	TENANT_SLUG_EXISTS     ResponseCode = "TENANT_SLUG_EXISTS"
	TENANT_DOMAIN_EXISTS   ResponseCode = "TENANT_DOMAIN_EXISTS"
	TENANT_INVALID_ID      ResponseCode = "TENANT_INVALID_ID"
	TENANT_INVALID_SLUG    ResponseCode = "TENANT_INVALID_SLUG"
	TENANT_CREATION_FAILED ResponseCode = "TENANT_CREATION_FAILED"
	TENANT_UPDATE_FAILED   ResponseCode = "TENANT_UPDATE_FAILED"
	TENANT_DELETE_FAILED   ResponseCode = "TENANT_DELETE_FAILED"
	TENANT_QUOTA_EXCEEDED  ResponseCode = "TENANT_QUOTA_EXCEEDED"
	TENANT_ACCESS_DENIED   ResponseCode = "TENANT_ACCESS_DENIED"
)

// Role-related codes
const (
	// Role success codes
	ROLE_CREATED       ResponseCode = "ROLE_CREATED"
	ROLE_UPDATED       ResponseCode = "ROLE_UPDATED"
	ROLE_DELETED       ResponseCode = "ROLE_DELETED"
	ROLE_RETRIEVED     ResponseCode = "ROLE_RETRIEVED"
	ROLES_LISTED       ResponseCode = "ROLES_LISTED"
	ROLE_ASSIGNED      ResponseCode = "ROLE_ASSIGNED"
	ROLE_REVOKED       ResponseCode = "ROLE_REVOKED"
	ROLES_BULK_CREATED ResponseCode = "ROLES_BULK_CREATED"
	ROLES_BULK_DELETED ResponseCode = "ROLES_BULK_DELETED"
	ROLES_INITIALIZED  ResponseCode = "ROLES_INITIALIZED"

	// Role error codes
	ROLE_NOT_FOUND         ResponseCode = "ROLE_NOT_FOUND"
	ROLE_ALREADY_EXISTS    ResponseCode = "ROLE_ALREADY_EXISTS"
	ROLE_SLUG_EXISTS       ResponseCode = "ROLE_SLUG_EXISTS"
	ROLE_INVALID_ID        ResponseCode = "ROLE_INVALID_ID"
	ROLE_INVALID_SLUG      ResponseCode = "ROLE_INVALID_SLUG"
	ROLE_CREATION_FAILED   ResponseCode = "ROLE_CREATION_FAILED"
	ROLE_UPDATE_FAILED     ResponseCode = "ROLE_UPDATE_FAILED"
	ROLE_DELETE_FAILED     ResponseCode = "ROLE_DELETE_FAILED"
	ROLE_ASSIGNMENT_FAILED ResponseCode = "ROLE_ASSIGNMENT_FAILED"
	ROLE_REVOCATION_FAILED ResponseCode = "ROLE_REVOCATION_FAILED"
	ROLE_SYSTEM_ROLE       ResponseCode = "ROLE_SYSTEM_ROLE"
	ROLE_CANNOT_DELETE     ResponseCode = "ROLE_CANNOT_DELETE"
)

// Permission-related codes
const (
	// Permission success codes
	PERMISSION_CREATED   ResponseCode = "PERMISSION_CREATED"
	PERMISSION_UPDATED   ResponseCode = "PERMISSION_UPDATED"
	PERMISSION_DELETED   ResponseCode = "PERMISSION_DELETED"
	PERMISSION_RETRIEVED ResponseCode = "PERMISSION_RETRIEVED"
	PERMISSIONS_LISTED   ResponseCode = "PERMISSIONS_LISTED"
	PERMISSION_ASSIGNED  ResponseCode = "PERMISSION_ASSIGNED"
	PERMISSION_REVOKED   ResponseCode = "PERMISSION_REVOKED"
	PERMISSIONS_REPLACED ResponseCode = "PERMISSIONS_REPLACED"

	// Permission error codes
	PERMISSION_NOT_FOUND         ResponseCode = "PERMISSION_NOT_FOUND"
	PERMISSION_ALREADY_EXISTS    ResponseCode = "PERMISSION_ALREADY_EXISTS"
	PERMISSION_INVALID_ID        ResponseCode = "PERMISSION_INVALID_ID"
	PERMISSION_CREATION_FAILED   ResponseCode = "PERMISSION_CREATION_FAILED"
	PERMISSION_UPDATE_FAILED     ResponseCode = "PERMISSION_UPDATE_FAILED"
	PERMISSION_DELETE_FAILED     ResponseCode = "PERMISSION_DELETE_FAILED"
	PERMISSION_ASSIGNMENT_FAILED ResponseCode = "PERMISSION_ASSIGNMENT_FAILED"
	PERMISSION_REVOCATION_FAILED ResponseCode = "PERMISSION_REVOCATION_FAILED"
	PERMISSION_ACCESS_DENIED     ResponseCode = "PERMISSION_ACCESS_DENIED"
	PERMISSION_INSUFFICIENT      ResponseCode = "PERMISSION_INSUFFICIENT"
)

// Validation codes
const (
	VALIDATION_ERROR               ResponseCode = "VALIDATION_ERROR"
	VALIDATION_FAILED              ResponseCode = "VALIDATION_FAILED"
	VALIDATION_FIELD_REQUIRED      ResponseCode = "VALIDATION_FIELD_REQUIRED"
	VALIDATION_FIELD_INVALID       ResponseCode = "VALIDATION_FIELD_INVALID"
	VALIDATION_EMAIL_INVALID       ResponseCode = "VALIDATION_EMAIL_INVALID"
	VALIDATION_PASSWORD_WEAK       ResponseCode = "VALIDATION_PASSWORD_WEAK"
	VALIDATION_LENGTH_EXCEEDED     ResponseCode = "VALIDATION_LENGTH_EXCEEDED"
	VALIDATION_LENGTH_INSUFFICIENT ResponseCode = "VALIDATION_LENGTH_INSUFFICIENT"
)

// System codes
const (
	// System success codes
	SYSTEM_HEALTHY ResponseCode = "SYSTEM_HEALTHY"
	SYSTEM_READY   ResponseCode = "SYSTEM_READY"

	// System error codes
	SYSTEM_ERROR               ResponseCode = "SYSTEM_ERROR"
	SYSTEM_UNAVAILABLE         ResponseCode = "SYSTEM_UNAVAILABLE"
	SYSTEM_MAINTENANCE         ResponseCode = "SYSTEM_MAINTENANCE"
	DATABASE_ERROR             ResponseCode = "DATABASE_ERROR"
	DATABASE_CONNECTION_FAILED ResponseCode = "DATABASE_CONNECTION_FAILED"
	REDIS_ERROR                ResponseCode = "REDIS_ERROR"
	REDIS_CONNECTION_FAILED    ResponseCode = "REDIS_CONNECTION_FAILED"
	EXTERNAL_SERVICE_ERROR     ResponseCode = "EXTERNAL_SERVICE_ERROR"
)

// General error codes
const (
	BAD_REQUEST           ResponseCode = "BAD_REQUEST"
	UNAUTHORIZED          ResponseCode = "UNAUTHORIZED"
	FORBIDDEN             ResponseCode = "FORBIDDEN"
	NOT_FOUND             ResponseCode = "NOT_FOUND"
	METHOD_NOT_ALLOWED    ResponseCode = "METHOD_NOT_ALLOWED"
	CONFLICT              ResponseCode = "CONFLICT"
	UNPROCESSABLE_ENTITY  ResponseCode = "UNPROCESSABLE_ENTITY"
	TOO_MANY_REQUESTS     ResponseCode = "TOO_MANY_REQUESTS"
	INTERNAL_SERVER_ERROR ResponseCode = "INTERNAL_SERVER_ERROR"
	SERVICE_UNAVAILABLE   ResponseCode = "SERVICE_UNAVAILABLE"
	GATEWAY_TIMEOUT       ResponseCode = "GATEWAY_TIMEOUT"
)

// Request codes
const (
	REQUEST_INVALID        ResponseCode = "REQUEST_INVALID"
	REQUEST_MALFORMED      ResponseCode = "REQUEST_MALFORMED"
	REQUEST_BODY_INVALID   ResponseCode = "REQUEST_BODY_INVALID"
	REQUEST_PARAM_MISSING  ResponseCode = "REQUEST_PARAM_MISSING"
	REQUEST_PARAM_INVALID  ResponseCode = "REQUEST_PARAM_INVALID"
	REQUEST_HEADER_MISSING ResponseCode = "REQUEST_HEADER_MISSING"
	REQUEST_HEADER_INVALID ResponseCode = "REQUEST_HEADER_INVALID"
)
